{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'bgTemplate',
          'title':'WORLD EDITOR',
          'size':(700, 650),
          'statusBar':1,
          'visible':0,

         'components': [

{'type':'Button', 
    'name':'cmdSizeOK', 
    'position':(365, 20), 
    'size':(35, 28), 
    'label':'OK', 
    },

{'type':'TextField', 
    'name':'txtMapSize', 
    'position':(280, 35), 
    'size':(75, -1), 
    'text':'10x10', 
    },

{'type':'StaticText', 
    'name':'StaticText1', 
    'position':(225, 15), 
    'text':'Map size:', 
    },

{'type':'Choice', 
    'name':'mapSize', 
    'position':(280, 10), 
    'size':(75, -1), 
    'items':['150x150', '100x100', '50x50', 'custom'], 
    'stringSelection':'150x150', 
    },

{'type':'ImageButton', 
    'name':'cmdExportXML', 
    'position':(170, 5), 
    'size':(30, 30), 
    'border':'3d', 
    'file':'iconos/exit.png', 
    'toolTip':'Export', 
    },

{'type':'Button', 
    'name':'cmdTileset', 
    'position':(570, 10), 
    'label':'Tileset...', 
    },

{'type':'ImageButton', 
    'name':'cmdQuit', 
    'position':(130, 5), 
    'size':(30, 30), 
    'border':'3d', 
    'file':'iconos/exit.png', 
    'toolTip':'Exit', 
    },

{'type':'ImageButton', 
    'name':'cmdNew', 
    'position':(10, 5), 
    'size':(30, 30), 
    'border':'3d', 
    'file':'iconos/exec.png', 
    'toolTip':'New Map', 
    },

{'type':'ImageButton', 
    'name':'cmdSave', 
    'position':(90, 5), 
    'size':(30, 30), 
    'border':'3d', 
    'file':'iconos/filesave.png', 
    'toolTip':'Save Map', 
    },

{'type':'ImageButton', 
    'name':'cmdOpen', 
    'position':(50, 5), 
    'size':(30, 30), 
    'border':'3d', 
    'file':'iconos/fileopen.png', 
    'toolTip':'Open Map', 
    },

{'type':'StaticText', 
    'name':'lblMapCoords', 
    'position':(510, 15), 
    'text':'Coords:', 
    },

{'type':'Slider', 
    'name':'sliderY', 
    'position':(650, 50), 
    'size':(-1, 495), 
    'labels':False, 
    'layout':'vertical', 
    'max':85, 
    'min':0, 
    'tickFrequency':0, 
    'ticks':True, 
    'value':0, 
    },

{'type':'Slider', 
    'name':'sliderX', 
    'position':(-5, 540), 
    'size':(660, -1), 
    'labels':False, 
    'layout':'horizontal', 
    'max':80, 
    'min':0, 
    'tickFrequency':0, 
    'ticks':True, 
    'value':0, 
    },

{'type':'BitmapCanvas', 
    'name':'worldMap', 
    'position':(5, 60), 
    'size':(640, 480), 
    'backgroundColor':(255, 255, 255), 
    },

] # end components
} # end background
] # end backgrounds
} }
